openapi: 3.0.2
info:
  title: Hello API
  description: A simple API that returns a greeting
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /hello:
    get:
      summary: Returns a hello message
      operationId: getHello
      security:
        - BearerAuth: []
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World!"
